ERROR - 2025-02-18 16:46:35,736 - Erro ao fazer login: Alert Text: Usuário ou Senha Inválida.
Message: unexpected alert open: {Alert text : Usuário ou Senha Inválida.}
  (Session info: chrome=133.0.6943.98)
Stacktrace:
	GetHandleVerifier [0x00007FF7346D6F15+28773]
	(No symbol) [0x00007FF734642600]
	(No symbol) [0x00007FF7344D8FAA]
	(No symbol) [0x00007FF73458033B]
	(No symbol) [0x00007FF734557023]
	(No symbol) [0x00007FF73451FF5E]
	(No symbol) [0x00007FF7345211E3]
	GetHandleVerifier [0x00007FF734A2425D+3490733]
	GetHandleVerifier [0x00007FF734A3BA43+3586963]
	GetHandleVerifier [0x00007FF734A3147D+3544525]
	GetHandleVerifier [0x00007FF73479C9DA+838442]
	(No symbol) [0x00007FF73464D04F]
	(No symbol) [0x00007FF734649614]
	(No symbol) [0x00007FF7346497B6]
	(No symbol) [0x00007FF734638CE9]
	BaseThreadInitThunk [0x00007FFD75B57374+20]
	RtlUserThreadStart [0x00007FFD75E1CC91+33]
Traceback (most recent call last):
  File "d:\Users\marcos.fernandes\TRIBUNAL SUPERIOR ELEITORAL\NPD - Documents\Núcleo de Pesquisa e Desenvolvimento da SAD\3. Desenvolvimento\6. Automações Python\Projeto SEARE\workspace-projeto-seare\Main\Utils\sei_automation_utils.py", line 41, in logar_sei
    if("controlador.php?") in self.navegador.current_url: #Verifica se na url contém a string definida, se tiver quer dizer que o login foi bem-sucedido
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 560, in current_url
    return self.execute(Command.GET_CURRENT_URL)["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 231, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: Usuário ou Senha Inválida.
Message: unexpected alert open: {Alert text : Usuário ou Senha Inválida.}
  (Session info: chrome=133.0.6943.98)
Stacktrace:
	GetHandleVerifier [0x00007FF7346D6F15+28773]
	(No symbol) [0x00007FF734642600]
	(No symbol) [0x00007FF7344D8FAA]
	(No symbol) [0x00007FF73458033B]
	(No symbol) [0x00007FF734557023]
	(No symbol) [0x00007FF73451FF5E]
	(No symbol) [0x00007FF7345211E3]
	GetHandleVerifier [0x00007FF734A2425D+3490733]
	GetHandleVerifier [0x00007FF734A3BA43+3586963]
	GetHandleVerifier [0x00007FF734A3147D+3544525]
	GetHandleVerifier [0x00007FF73479C9DA+838442]
	(No symbol) [0x00007FF73464D04F]
	(No symbol) [0x00007FF734649614]
	(No symbol) [0x00007FF7346497B6]
	(No symbol) [0x00007FF734638CE9]
	BaseThreadInitThunk [0x00007FFD75B57374+20]
	RtlUserThreadStart [0x00007FFD75E1CC91+33]

ERROR - 2025-02-18 16:47:40,470 - Erro ao buscar título para NSEI 2023.00.000012906-3: Object of type method is not JSON serializable
Traceback (most recent call last):
  File "d:\Users\marcos.fernandes\TRIBUNAL SUPERIOR ELEITORAL\NPD - Documents\Núcleo de Pesquisa e Desenvolvimento da SAD\3. Desenvolvimento\6. Automações Python\Projeto SEARE\workspace-projeto-seare\Main\Utils\sei_automation_utils.py", line 65, in buscar_titulos
    titulo = self.navegador.execute_script(self.get_title_script)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 528, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 427, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 400, in execute
    data = utils.dump_json(params)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\utils.py", line 24, in dump_json
    return json.dumps(json_struct)
           ~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type method is not JSON serializable
ERROR - 2025-02-18 16:49:28,725 - Erro ao buscar título para NSEI 2023.00.000012906-3: Object of type method is not JSON serializable
Traceback (most recent call last):
  File "d:\Users\marcos.fernandes\TRIBUNAL SUPERIOR ELEITORAL\NPD - Documents\Núcleo de Pesquisa e Desenvolvimento da SAD\3. Desenvolvimento\6. Automações Python\Projeto SEARE\workspace-projeto-seare\Main\Utils\sei_automation_utils.py", line 65, in buscar_titulos
    titulo = self.navegador.execute_script(self.get_title_script)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 528, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 427, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 400, in execute
    data = utils.dump_json(params)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\utils.py", line 24, in dump_json
    return json.dumps(json_struct)
           ~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type method is not JSON serializable
ERROR - 2025-02-18 16:50:59,820 - Erro ao buscar título para NSEI 2023.00.000012906-3: Object of type method is not JSON serializable
Traceback (most recent call last):
  File "d:\Users\marcos.fernandes\TRIBUNAL SUPERIOR ELEITORAL\NPD - Documents\Núcleo de Pesquisa e Desenvolvimento da SAD\3. Desenvolvimento\6. Automações Python\Projeto SEARE\workspace-projeto-seare\Main\Utils\sei_automation_utils.py", line 65, in buscar_titulos
    titulo = self.navegador.execute_script(self.get_title_script)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 528, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 427, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 400, in execute
    data = utils.dump_json(params)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\utils.py", line 24, in dump_json
    return json.dumps(json_struct)
           ~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type method is not JSON serializable
ERROR - 2025-02-18 16:52:24,376 - Erro ao buscar título para NSEI 2023.00.000012906-3: Object of type method is not JSON serializable
Traceback (most recent call last):
  File "d:\Users\marcos.fernandes\TRIBUNAL SUPERIOR ELEITORAL\NPD - Documents\Núcleo de Pesquisa e Desenvolvimento da SAD\3. Desenvolvimento\6. Automações Python\Projeto SEARE\workspace-projeto-seare\Main\Utils\sei_automation_utils.py", line 65, in buscar_titulos
    titulo = self.navegador.execute_script(self.get_title_script)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 528, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 427, in execute
    response = self.command_executor.execute(driver_command, params)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 400, in execute
    data = utils.dump_json(params)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\utils.py", line 24, in dump_json
    return json.dumps(json_struct)
           ~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
                    f'is not JSON serializable')
TypeError: Object of type method is not JSON serializable
ERROR - 2025-03-21 12:30:25,942 - Erro ao fazer login: Alert Text: Usuário ou Senha Inválida.
Message: unexpected alert open: {Alert text : Usuário ou Senha Inválida.}
  (Session info: chrome=134.0.6998.118)
Stacktrace:
	GetHandleVerifier [0x00007FF71D1C6F15+28773]
	(No symbol) [0x00007FF71D132600]
	(No symbol) [0x00007FF71CFC8FAA]
	(No symbol) [0x00007FF71D07033B]
	(No symbol) [0x00007FF71D047023]
	(No symbol) [0x00007FF71D00FF5E]
	(No symbol) [0x00007FF71D0111E3]
	GetHandleVerifier [0x00007FF71D51425D+3490733]
	GetHandleVerifier [0x00007FF71D52BA43+3586963]
	GetHandleVerifier [0x00007FF71D52147D+3544525]
	GetHandleVerifier [0x00007FF71D28C9DA+838442]
	(No symbol) [0x00007FF71D13D04F]
	(No symbol) [0x00007FF71D139614]
	(No symbol) [0x00007FF71D1397B6]
	(No symbol) [0x00007FF71D128CE9]
	BaseThreadInitThunk [0x00007FFD71777374+20]
	RtlUserThreadStart [0x00007FFD7329CC91+33]
Traceback (most recent call last):
  File "Main\Utils\sei_automation_utils.py", line 41, in logar_sei
    if("controlador.php?") in self.navegador.current_url: #Verifica se na url contém a string definida, se tiver quer dizer que o login foi bem-sucedido
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "selenium\webdriver\remote\webdriver.py", line 560, in current_url
  File "selenium\webdriver\remote\webdriver.py", line 429, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 231, in check_response
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: Usuário ou Senha Inválida.
Message: unexpected alert open: {Alert text : Usuário ou Senha Inválida.}
  (Session info: chrome=134.0.6998.118)
Stacktrace:
	GetHandleVerifier [0x00007FF71D1C6F15+28773]
	(No symbol) [0x00007FF71D132600]
	(No symbol) [0x00007FF71CFC8FAA]
	(No symbol) [0x00007FF71D07033B]
	(No symbol) [0x00007FF71D047023]
	(No symbol) [0x00007FF71D00FF5E]
	(No symbol) [0x00007FF71D0111E3]
	GetHandleVerifier [0x00007FF71D51425D+3490733]
	GetHandleVerifier [0x00007FF71D52BA43+3586963]
	GetHandleVerifier [0x00007FF71D52147D+3544525]
	GetHandleVerifier [0x00007FF71D28C9DA+838442]
	(No symbol) [0x00007FF71D13D04F]
	(No symbol) [0x00007FF71D139614]
	(No symbol) [0x00007FF71D1397B6]
	(No symbol) [0x00007FF71D128CE9]
	BaseThreadInitThunk [0x00007FFD71777374+20]
	RtlUserThreadStart [0x00007FFD7329CC91+33]

ERROR - 2025-03-21 12:38:02,123 - Erro ao fazer login: Alert Text: Usuário ou Senha Inválida.
Message: unexpected alert open: {Alert text : Usuário ou Senha Inválida.}
  (Session info: chrome=134.0.6998.118)
Stacktrace:
	GetHandleVerifier [0x00007FF71D1C6F15+28773]
	(No symbol) [0x00007FF71D132600]
	(No symbol) [0x00007FF71CFC8FAA]
	(No symbol) [0x00007FF71D07033B]
	(No symbol) [0x00007FF71D047023]
	(No symbol) [0x00007FF71D00FF5E]
	(No symbol) [0x00007FF71D0111E3]
	GetHandleVerifier [0x00007FF71D51425D+3490733]
	GetHandleVerifier [0x00007FF71D52BA43+3586963]
	GetHandleVerifier [0x00007FF71D52147D+3544525]
	GetHandleVerifier [0x00007FF71D28C9DA+838442]
	(No symbol) [0x00007FF71D13D04F]
	(No symbol) [0x00007FF71D139614]
	(No symbol) [0x00007FF71D1397B6]
	(No symbol) [0x00007FF71D128CE9]
	BaseThreadInitThunk [0x00007FFD71777374+20]
	RtlUserThreadStart [0x00007FFD7329CC91+33]
Traceback (most recent call last):
  File "Main\Utils\sei_automation_utils.py", line 41, in logar_sei
    if("controlador.php?") in self.navegador.current_url: #Verifica se na url contém a string definida, se tiver quer dizer que o login foi bem-sucedido
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "selenium\webdriver\remote\webdriver.py", line 560, in current_url
  File "selenium\webdriver\remote\webdriver.py", line 429, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 231, in check_response
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: Usuário ou Senha Inválida.
Message: unexpected alert open: {Alert text : Usuário ou Senha Inválida.}
  (Session info: chrome=134.0.6998.118)
Stacktrace:
	GetHandleVerifier [0x00007FF71D1C6F15+28773]
	(No symbol) [0x00007FF71D132600]
	(No symbol) [0x00007FF71CFC8FAA]
	(No symbol) [0x00007FF71D07033B]
	(No symbol) [0x00007FF71D047023]
	(No symbol) [0x00007FF71D00FF5E]
	(No symbol) [0x00007FF71D0111E3]
	GetHandleVerifier [0x00007FF71D51425D+3490733]
	GetHandleVerifier [0x00007FF71D52BA43+3586963]
	GetHandleVerifier [0x00007FF71D52147D+3544525]
	GetHandleVerifier [0x00007FF71D28C9DA+838442]
	(No symbol) [0x00007FF71D13D04F]
	(No symbol) [0x00007FF71D139614]
	(No symbol) [0x00007FF71D1397B6]
	(No symbol) [0x00007FF71D128CE9]
	BaseThreadInitThunk [0x00007FFD71777374+20]
	RtlUserThreadStart [0x00007FFD7329CC91+33]

ERROR - 2025-03-21 12:53:43,476 - Erro ao fazer login: Alert Text: Usuário ou Senha Inválida.
Message: unexpected alert open: {Alert text : Usuário ou Senha Inválida.}
  (Session info: chrome=134.0.6998.118)
Stacktrace:
	GetHandleVerifier [0x00007FF71D1C6F15+28773]
	(No symbol) [0x00007FF71D132600]
	(No symbol) [0x00007FF71CFC8FAA]
	(No symbol) [0x00007FF71D07033B]
	(No symbol) [0x00007FF71D047023]
	(No symbol) [0x00007FF71D00FF5E]
	(No symbol) [0x00007FF71D0111E3]
	GetHandleVerifier [0x00007FF71D51425D+3490733]
	GetHandleVerifier [0x00007FF71D52BA43+3586963]
	GetHandleVerifier [0x00007FF71D52147D+3544525]
	GetHandleVerifier [0x00007FF71D28C9DA+838442]
	(No symbol) [0x00007FF71D13D04F]
	(No symbol) [0x00007FF71D139614]
	(No symbol) [0x00007FF71D1397B6]
	(No symbol) [0x00007FF71D128CE9]
	BaseThreadInitThunk [0x00007FFD71777374+20]
	RtlUserThreadStart [0x00007FFD7329CC91+33]
Traceback (most recent call last):
  File "Main\Utils\sei_automation_utils.py", line 41, in logar_sei
    if("controlador.php?") in self.navegador.current_url: #Verifica se na url contém a string definida, se tiver quer dizer que o login foi bem-sucedido
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "selenium\webdriver\remote\webdriver.py", line 560, in current_url
  File "selenium\webdriver\remote\webdriver.py", line 429, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 231, in check_response
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: Usuário ou Senha Inválida.
Message: unexpected alert open: {Alert text : Usuário ou Senha Inválida.}
  (Session info: chrome=134.0.6998.118)
Stacktrace:
	GetHandleVerifier [0x00007FF71D1C6F15+28773]
	(No symbol) [0x00007FF71D132600]
	(No symbol) [0x00007FF71CFC8FAA]
	(No symbol) [0x00007FF71D07033B]
	(No symbol) [0x00007FF71D047023]
	(No symbol) [0x00007FF71D00FF5E]
	(No symbol) [0x00007FF71D0111E3]
	GetHandleVerifier [0x00007FF71D51425D+3490733]
	GetHandleVerifier [0x00007FF71D52BA43+3586963]
	GetHandleVerifier [0x00007FF71D52147D+3544525]
	GetHandleVerifier [0x00007FF71D28C9DA+838442]
	(No symbol) [0x00007FF71D13D04F]
	(No symbol) [0x00007FF71D139614]
	(No symbol) [0x00007FF71D1397B6]
	(No symbol) [0x00007FF71D128CE9]
	BaseThreadInitThunk [0x00007FFD71777374+20]
	RtlUserThreadStart [0x00007FFD7329CC91+33]

ERROR - 2025-03-24 11:45:42,038 - Erro ao buscar título para NSEI 2023.00.000007586-9: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: chrome=134.0.6998.118)
Stacktrace:
	GetHandleVerifier [0x00007FF6E04E6F15+28773]
	(No symbol) [0x00007FF6E0452600]
	(No symbol) [0x00007FF6E02E8FAA]
	(No symbol) [0x00007FF6E02D4DA5]
	(No symbol) [0x00007FF6E02F973A]
	(No symbol) [0x00007FF6E036EFDF]
	(No symbol) [0x00007FF6E038EFE2]
	(No symbol) [0x00007FF6E0367023]
	(No symbol) [0x00007FF6E032FF5E]
	(No symbol) [0x00007FF6E03311E3]
	GetHandleVerifier [0x00007FF6E083425D+3490733]
	GetHandleVerifier [0x00007FF6E084BA43+3586963]
	GetHandleVerifier [0x00007FF6E084147D+3544525]
	GetHandleVerifier [0x00007FF6E05AC9DA+838442]
	(No symbol) [0x00007FF6E045D04F]
	(No symbol) [0x00007FF6E0459614]
	(No symbol) [0x00007FF6E04597B6]
	(No symbol) [0x00007FF6E0448CE9]
	BaseThreadInitThunk [0x00007FF8BCA37374+20]
	RtlUserThreadStart [0x00007FF8BCFBCC91+33]
Traceback (most recent call last):
  File "d:\Users\marcos.fernandes\TRIBUNAL SUPERIOR ELEITORAL\NPD - Documents\Núcleo de Pesquisa e Desenvolvimento da SAD\3. Desenvolvimento\6. Automações Python\Projeto SEARE\workspace-projeto-seare\Main\Utils\sei_automation_utils.py", line 64, in buscar_titulos
    iframe = self.navegador.find_element(By.CSS_SELECTOR, "#divInfraAreaGlobal #divInfraAreaTela #divInfraAreaTelaD #divIframeArvore #ifrArvore") #Navega pelo HTML para encontrar o iframe
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: chrome=134.0.6998.118)
Stacktrace:
	GetHandleVerifier [0x00007FF6E04E6F15+28773]
	(No symbol) [0x00007FF6E0452600]
	(No symbol) [0x00007FF6E02E8FAA]
	(No symbol) [0x00007FF6E02D4DA5]
	(No symbol) [0x00007FF6E02F973A]
	(No symbol) [0x00007FF6E036EFDF]
	(No symbol) [0x00007FF6E038EFE2]
	(No symbol) [0x00007FF6E0367023]
	(No symbol) [0x00007FF6E032FF5E]
	(No symbol) [0x00007FF6E03311E3]
	GetHandleVerifier [0x00007FF6E083425D+3490733]
	GetHandleVerifier [0x00007FF6E084BA43+3586963]
	GetHandleVerifier [0x00007FF6E084147D+3544525]
	GetHandleVerifier [0x00007FF6E05AC9DA+838442]
	(No symbol) [0x00007FF6E045D04F]
	(No symbol) [0x00007FF6E0459614]
	(No symbol) [0x00007FF6E04597B6]
	(No symbol) [0x00007FF6E0448CE9]
	BaseThreadInitThunk [0x00007FF8BCA37374+20]
	RtlUserThreadStart [0x00007FF8BCFBCC91+33]

ERROR - 2025-04-28 15:42:48,813 - Erro ao fazer login: Message: 
Traceback (most recent call last):
  File "Main\Utils\sei_automation_utils.py", line 45, in logar_sei
    WebDriverWait(self.navegador, 30).until(EC.url_changes(self.navegador.current_url))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "selenium\webdriver\support\wait.py", line 146, in until
selenium.common.exceptions.TimeoutException: Message: 

ERROR - 2025-04-28 16:00:01,497 - Erro ao fazer login: Message: 
Traceback (most recent call last):
  File "d:\Users\marcos.fernandes\TRIBUNAL SUPERIOR ELEITORAL\NPD - Documents\Núcleo de Pesquisa e Desenvolvimento da SAD\3. Desenvolvimento\6. Automações Python\Projeto SEARE\workspace-projeto-seare\Main\Utils\sei_automation_utils.py", line 47, in logar_sei
    WebDriverWait(self.navegador, 30).until(EC.url_changes(self.navegador.current_url))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

ERROR - 2025-04-28 16:12:47,425 - Erro ao fazer login: Message: 
Traceback (most recent call last):
  File "d:\Users\marcos.fernandes\TRIBUNAL SUPERIOR ELEITORAL\NPD - Documents\Núcleo de Pesquisa e Desenvolvimento da SAD\3. Desenvolvimento\6. Automações Python\Projeto SEARE\workspace-projeto-seare\Main\Utils\sei_automation_utils.py", line 55, in logar_sei
    WebDriverWait(self.navegador, 30).until(EC.url_changes(self.navegador.current_url))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

ERROR - 2025-04-28 16:17:34,318 - Erro ao fazer login: Message: 
Traceback (most recent call last):
  File "d:\Users\marcos.fernandes\TRIBUNAL SUPERIOR ELEITORAL\NPD - Documents\Núcleo de Pesquisa e Desenvolvimento da SAD\3. Desenvolvimento\6. Automações Python\Projeto SEARE\workspace-projeto-seare\Main\Utils\sei_automation_utils.py", line 58, in logar_sei
    WebDriverWait(self.navegador, 30).until(EC.url_changes(self.navegador.current_url))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\support\wait.py", line 146, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

ERROR - 2025-04-28 16:27:12,605 - Erro ao fazer login: Message: 
Traceback (most recent call last):
  File "Main\Utils\sei_automation_utils.py", line 58, in logar_sei
    WebDriverWait(self.navegador, 30).until(EC.url_changes(self.navegador.current_url))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "selenium\webdriver\support\wait.py", line 146, in until
selenium.common.exceptions.TimeoutException: Message: 

ERROR - 2025-04-28 16:34:21,560 - Erro ao fazer login: Message: 
Traceback (most recent call last):
  File "Main\Utils\sei_automation_utils.py", line 60, in logar_sei
    WebDriverWait(self.navegador, 30).until(EC.url_changes(self.navegador.current_url))
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "selenium\webdriver\support\wait.py", line 146, in until
selenium.common.exceptions.TimeoutException: Message: 

ERROR - 2025-04-28 17:33:25,053 - Erro ao buscar título para NSEI 2023.00.000002355-9: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#divInfraAreaGlobal #divInfraAreaTela #divInfraAreaTelaD #divIframeArvore #ifrArvore"}
  (Session info: chrome=135.0.7049.115); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x008CD363+60275]
	GetHandleVerifier [0x008CD3A4+60340]
	(No symbol) [0x007006F3]
	(No symbol) [0x00748690]
	(No symbol) [0x00748A2B]
	(No symbol) [0x00790EE2]
	(No symbol) [0x0076D0D4]
	(No symbol) [0x0078E6EB]
	(No symbol) [0x0076CE86]
	(No symbol) [0x0073C623]
	(No symbol) [0x0073D474]
	GetHandleVerifier [0x00B18FE3+2467827]
	GetHandleVerifier [0x00B145E6+2448886]
	GetHandleVerifier [0x00B2F80C+2560028]
	GetHandleVerifier [0x008E3DF5+153093]
	GetHandleVerifier [0x008EA3BD+179149]
	GetHandleVerifier [0x008D4BB8+91080]
	GetHandleVerifier [0x008D4D60+91504]
	GetHandleVerifier [0x008BFA10+4640]
	BaseThreadInitThunk [0x75F6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77DF809E+286]
	RtlGetAppContainerNamedObjectPath [0x77DF806E+238]
Traceback (most recent call last):
  File "Main\Utils\sei_automation_utils.py", line 86, in buscar_titulos
    iframe = self.navegador.find_element(By.CSS_SELECTOR, "#divInfraAreaGlobal #divInfraAreaTela #divInfraAreaTelaD #divIframeArvore #ifrArvore") #Navega pelo HTML para encontrar o iframe
  File "selenium\webdriver\remote\webdriver.py", line 888, in find_element
  File "selenium\webdriver\remote\webdriver.py", line 429, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 232, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#divInfraAreaGlobal #divInfraAreaTela #divInfraAreaTelaD #divIframeArvore #ifrArvore"}
  (Session info: chrome=135.0.7049.115); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x008CD363+60275]
	GetHandleVerifier [0x008CD3A4+60340]
	(No symbol) [0x007006F3]
	(No symbol) [0x00748690]
	(No symbol) [0x00748A2B]
	(No symbol) [0x00790EE2]
	(No symbol) [0x0076D0D4]
	(No symbol) [0x0078E6EB]
	(No symbol) [0x0076CE86]
	(No symbol) [0x0073C623]
	(No symbol) [0x0073D474]
	GetHandleVerifier [0x00B18FE3+2467827]
	GetHandleVerifier [0x00B145E6+2448886]
	GetHandleVerifier [0x00B2F80C+2560028]
	GetHandleVerifier [0x008E3DF5+153093]
	GetHandleVerifier [0x008EA3BD+179149]
	GetHandleVerifier [0x008D4BB8+91080]
	GetHandleVerifier [0x008D4D60+91504]
	GetHandleVerifier [0x008BFA10+4640]
	BaseThreadInitThunk [0x75F6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77DF809E+286]
	RtlGetAppContainerNamedObjectPath [0x77DF806E+238]

ERROR - 2025-04-28 17:57:37,623 - Erro ao buscar título para NSEI 2023.00.000002355-9: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#divInfraAreaGlobal #divInfraAreaTela #divInfraAreaTelaD #divIframeArvore #ifrArvore"}
  (Session info: chrome=135.0.7049.115); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x008CD363+60275]
	GetHandleVerifier [0x008CD3A4+60340]
	(No symbol) [0x007006F3]
	(No symbol) [0x00748690]
	(No symbol) [0x00748A2B]
	(No symbol) [0x00790EE2]
	(No symbol) [0x0076D0D4]
	(No symbol) [0x0078E6EB]
	(No symbol) [0x0076CE86]
	(No symbol) [0x0073C623]
	(No symbol) [0x0073D474]
	GetHandleVerifier [0x00B18FE3+2467827]
	GetHandleVerifier [0x00B145E6+2448886]
	GetHandleVerifier [0x00B2F80C+2560028]
	GetHandleVerifier [0x008E3DF5+153093]
	GetHandleVerifier [0x008EA3BD+179149]
	GetHandleVerifier [0x008D4BB8+91080]
	GetHandleVerifier [0x008D4D60+91504]
	GetHandleVerifier [0x008BFA10+4640]
	BaseThreadInitThunk [0x75F6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77DF809E+286]
	RtlGetAppContainerNamedObjectPath [0x77DF806E+238]
Traceback (most recent call last):
  File "d:\Users\marcos.fernandes\TRIBUNAL SUPERIOR ELEITORAL\NPD - Documents\Núcleo de Pesquisa e Desenvolvimento da SAD\3. Desenvolvimento\6. Automações Python\Projeto SEARE\workspace-projeto-seare\Main\Utils\sei_automation_utils.py", line 87, in buscar_titulos
    iframe = self.navegador.find_element(By.CSS_SELECTOR, "#divInfraAreaGlobal #divInfraAreaTela #divInfraAreaTelaD #divIframeArvore #ifrArvore") #Navega pelo HTML para encontrar o iframe
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "D:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#divInfraAreaGlobal #divInfraAreaTela #divInfraAreaTelaD #divIframeArvore #ifrArvore"}
  (Session info: chrome=135.0.7049.115); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x008CD363+60275]
	GetHandleVerifier [0x008CD3A4+60340]
	(No symbol) [0x007006F3]
	(No symbol) [0x00748690]
	(No symbol) [0x00748A2B]
	(No symbol) [0x00790EE2]
	(No symbol) [0x0076D0D4]
	(No symbol) [0x0078E6EB]
	(No symbol) [0x0076CE86]
	(No symbol) [0x0073C623]
	(No symbol) [0x0073D474]
	GetHandleVerifier [0x00B18FE3+2467827]
	GetHandleVerifier [0x00B145E6+2448886]
	GetHandleVerifier [0x00B2F80C+2560028]
	GetHandleVerifier [0x008E3DF5+153093]
	GetHandleVerifier [0x008EA3BD+179149]
	GetHandleVerifier [0x008D4BB8+91080]
	GetHandleVerifier [0x008D4D60+91504]
	GetHandleVerifier [0x008BFA10+4640]
	BaseThreadInitThunk [0x75F6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77DF809E+286]
	RtlGetAppContainerNamedObjectPath [0x77DF806E+238]

ERROR - 2025-04-28 17:59:41,213 - Erro ao buscar título para NSEI 2023.00.000002355-9: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#divInfraAreaGlobal #divInfraAreaTela #divInfraAreaTelaD #divIframeArvore #ifrArvore"}
  (Session info: chrome=135.0.7049.115); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x008CD363+60275]
	GetHandleVerifier [0x008CD3A4+60340]
	(No symbol) [0x007006F3]
	(No symbol) [0x00748690]
	(No symbol) [0x00748A2B]
	(No symbol) [0x00790EE2]
	(No symbol) [0x0076D0D4]
	(No symbol) [0x0078E6EB]
	(No symbol) [0x0076CE86]
	(No symbol) [0x0073C623]
	(No symbol) [0x0073D474]
	GetHandleVerifier [0x00B18FE3+2467827]
	GetHandleVerifier [0x00B145E6+2448886]
	GetHandleVerifier [0x00B2F80C+2560028]
	GetHandleVerifier [0x008E3DF5+153093]
	GetHandleVerifier [0x008EA3BD+179149]
	GetHandleVerifier [0x008D4BB8+91080]
	GetHandleVerifier [0x008D4D60+91504]
	GetHandleVerifier [0x008BFA10+4640]
	BaseThreadInitThunk [0x75F6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77DF809E+286]
	RtlGetAppContainerNamedObjectPath [0x77DF806E+238]
Traceback (most recent call last):
  File "D:\Users\marcos.fernandes\TRIBUNAL SUPERIOR ELEITORAL\NPD - Documents\Núcleo de Pesquisa e Desenvolvimento da SAD\3. Desenvolvimento\6. Automações Python\Projeto SEARE\workspace-projeto-seare\Main\Utils\sei_automation_utils.py", line 87, in buscar_titulos
    iframe = self.navegador.find_element(By.CSS_SELECTOR, "#divInfraAreaGlobal #divInfraAreaTela #divInfraAreaTelaD #divIframeArvore #ifrArvore") #Navega pelo HTML para encontrar o iframe
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#divInfraAreaGlobal #divInfraAreaTela #divInfraAreaTelaD #divIframeArvore #ifrArvore"}
  (Session info: chrome=135.0.7049.115); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x008CD363+60275]
	GetHandleVerifier [0x008CD3A4+60340]
	(No symbol) [0x007006F3]
	(No symbol) [0x00748690]
	(No symbol) [0x00748A2B]
	(No symbol) [0x00790EE2]
	(No symbol) [0x0076D0D4]
	(No symbol) [0x0078E6EB]
	(No symbol) [0x0076CE86]
	(No symbol) [0x0073C623]
	(No symbol) [0x0073D474]
	GetHandleVerifier [0x00B18FE3+2467827]
	GetHandleVerifier [0x00B145E6+2448886]
	GetHandleVerifier [0x00B2F80C+2560028]
	GetHandleVerifier [0x008E3DF5+153093]
	GetHandleVerifier [0x008EA3BD+179149]
	GetHandleVerifier [0x008D4BB8+91080]
	GetHandleVerifier [0x008D4D60+91504]
	GetHandleVerifier [0x008BFA10+4640]
	BaseThreadInitThunk [0x75F6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77DF809E+286]
	RtlGetAppContainerNamedObjectPath [0x77DF806E+238]

ERROR - 2025-04-28 18:03:28,430 - Erro ao buscar título para NSEI 2023.00.000002355-9: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#divInfraAreaGlobal #divInfraAreaTela #divInfraAreaTelaD #divIframeArvore #ifrArvore"}
  (Session info: chrome=135.0.7049.115); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x008CD363+60275]
	GetHandleVerifier [0x008CD3A4+60340]
	(No symbol) [0x007006F3]
	(No symbol) [0x00748690]
	(No symbol) [0x00748A2B]
	(No symbol) [0x00790EE2]
	(No symbol) [0x0076D0D4]
	(No symbol) [0x0078E6EB]
	(No symbol) [0x0076CE86]
	(No symbol) [0x0073C623]
	(No symbol) [0x0073D474]
	GetHandleVerifier [0x00B18FE3+2467827]
	GetHandleVerifier [0x00B145E6+2448886]
	GetHandleVerifier [0x00B2F80C+2560028]
	GetHandleVerifier [0x008E3DF5+153093]
	GetHandleVerifier [0x008EA3BD+179149]
	GetHandleVerifier [0x008D4BB8+91080]
	GetHandleVerifier [0x008D4D60+91504]
	GetHandleVerifier [0x008BFA10+4640]
	BaseThreadInitThunk [0x75F6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77DF809E+286]
	RtlGetAppContainerNamedObjectPath [0x77DF806E+238]
Traceback (most recent call last):
  File "D:\Users\marcos.fernandes\TRIBUNAL SUPERIOR ELEITORAL\NPD - Documents\Núcleo de Pesquisa e Desenvolvimento da SAD\3. Desenvolvimento\6. Automações Python\Projeto SEARE\workspace-projeto-seare\Main\Utils\sei_automation_utils.py", line 89, in buscar_titulos
    if self.navegador.find_element(By.CSS_SELECTOR, "#divInfraAreaGlobal #divInfraAreaTela #divInfraAreaTelaD #divIframeArvore #ifrArvore"):
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"#divInfraAreaGlobal #divInfraAreaTela #divInfraAreaTelaD #divIframeArvore #ifrArvore"}
  (Session info: chrome=135.0.7049.115); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x008CD363+60275]
	GetHandleVerifier [0x008CD3A4+60340]
	(No symbol) [0x007006F3]
	(No symbol) [0x00748690]
	(No symbol) [0x00748A2B]
	(No symbol) [0x00790EE2]
	(No symbol) [0x0076D0D4]
	(No symbol) [0x0078E6EB]
	(No symbol) [0x0076CE86]
	(No symbol) [0x0073C623]
	(No symbol) [0x0073D474]
	GetHandleVerifier [0x00B18FE3+2467827]
	GetHandleVerifier [0x00B145E6+2448886]
	GetHandleVerifier [0x00B2F80C+2560028]
	GetHandleVerifier [0x008E3DF5+153093]
	GetHandleVerifier [0x008EA3BD+179149]
	GetHandleVerifier [0x008D4BB8+91080]
	GetHandleVerifier [0x008D4D60+91504]
	GetHandleVerifier [0x008BFA10+4640]
	BaseThreadInitThunk [0x75F6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77DF809E+286]
	RtlGetAppContainerNamedObjectPath [0x77DF806E+238]

ERROR - 2025-04-28 18:06:46,310 - Erro ao buscar título para NSEI 2023.00.000002355-9: Message: Processo Restrito
Traceback (most recent call last):
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\switch_to.py", line 88, in frame
    frame_reference = self._driver.find_element(By.ID, frame_reference)
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="Processo Restrito"]"}
  (Session info: chrome=135.0.7049.115); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x008CD363+60275]
	GetHandleVerifier [0x008CD3A4+60340]
	(No symbol) [0x007006F3]
	(No symbol) [0x00748690]
	(No symbol) [0x00748A2B]
	(No symbol) [0x00790EE2]
	(No symbol) [0x0076D0D4]
	(No symbol) [0x0078E6EB]
	(No symbol) [0x0076CE86]
	(No symbol) [0x0073C623]
	(No symbol) [0x0073D474]
	GetHandleVerifier [0x00B18FE3+2467827]
	GetHandleVerifier [0x00B145E6+2448886]
	GetHandleVerifier [0x00B2F80C+2560028]
	GetHandleVerifier [0x008E3DF5+153093]
	GetHandleVerifier [0x008EA3BD+179149]
	GetHandleVerifier [0x008D4BB8+91080]
	GetHandleVerifier [0x008D4D60+91504]
	GetHandleVerifier [0x008BFA10+4640]
	BaseThreadInitThunk [0x75F6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77DF809E+286]
	RtlGetAppContainerNamedObjectPath [0x77DF806E+238]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\switch_to.py", line 91, in frame
    frame_reference = self._driver.find_element(By.NAME, frame_reference)
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 888, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="Processo Restrito"]"}
  (Session info: chrome=135.0.7049.115); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
	GetHandleVerifier [0x008CD363+60275]
	GetHandleVerifier [0x008CD3A4+60340]
	(No symbol) [0x007006F3]
	(No symbol) [0x00748690]
	(No symbol) [0x00748A2B]
	(No symbol) [0x00790EE2]
	(No symbol) [0x0076D0D4]
	(No symbol) [0x0078E6EB]
	(No symbol) [0x0076CE86]
	(No symbol) [0x0073C623]
	(No symbol) [0x0073D474]
	GetHandleVerifier [0x00B18FE3+2467827]
	GetHandleVerifier [0x00B145E6+2448886]
	GetHandleVerifier [0x00B2F80C+2560028]
	GetHandleVerifier [0x008E3DF5+153093]
	GetHandleVerifier [0x008EA3BD+179149]
	GetHandleVerifier [0x008D4BB8+91080]
	GetHandleVerifier [0x008D4D60+91504]
	GetHandleVerifier [0x008BFA10+4640]
	BaseThreadInitThunk [0x75F6FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x77DF809E+286]
	RtlGetAppContainerNamedObjectPath [0x77DF806E+238]


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Users\marcos.fernandes\TRIBUNAL SUPERIOR ELEITORAL\NPD - Documents\Núcleo de Pesquisa e Desenvolvimento da SAD\3. Desenvolvimento\6. Automações Python\Projeto SEARE\workspace-projeto-seare\Main\Utils\sei_automation_utils.py", line 93, in buscar_titulos
    self.navegador.switch_to.frame(iframe) #Alterna o navegador para o iframe.
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\remote\switch_to.py", line 93, in frame
    raise NoSuchFrameException(frame_reference) from exc
selenium.common.exceptions.NoSuchFrameException: Message: Processo Restrito

ERROR - 2025-04-28 18:16:05,223 - Erro ao salvar o NSEIs: [Errno 13] Permission denied: 'D:\\Users\\marcos.fernandes\\TRIBUNAL SUPERIOR ELEITORAL\\NPD - Documents\\Núcleo de Pesquisa e Desenvolvimento da SAD\\3. Desenvolvimento\\6. Automações Python\\Projeto SEARE\\workspace-projeto-seare\\Main\\Dados\\Historico Varredura SEI.xlsx'
Traceback (most recent call last):
  File "D:\Users\marcos.fernandes\TRIBUNAL SUPERIOR ELEITORAL\NPD - Documents\Núcleo de Pesquisa e Desenvolvimento da SAD\3. Desenvolvimento\6. Automações Python\Projeto SEARE\workspace-projeto-seare\Main\Utils\excel_utils.py", line 50, in salvar_nsei_na_planilha
    workbook = load_workbook(excel_historico) #Carrega o arquivo excel especificado no parâmetro
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\reader\excel.py", line 346, in load_workbook
    reader = ExcelReader(filename, read_only, keep_vba,
                         data_only, keep_links, rich_text)
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\reader\excel.py", line 123, in __init__
    self.archive = _validate_archive(fn)
                   ~~~~~~~~~~~~~~~~~^^^^
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\site-packages\openpyxl\reader\excel.py", line 95, in _validate_archive
    archive = ZipFile(filename, 'r')
  File "d:\Users\marcos.fernandes\AppData\Local\Programs\Python\Python313\Lib\zipfile\__init__.py", line 1362, in __init__
    self.fp = io.open(file, filemode)
              ~~~~~~~^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'D:\\Users\\marcos.fernandes\\TRIBUNAL SUPERIOR ELEITORAL\\NPD - Documents\\Núcleo de Pesquisa e Desenvolvimento da SAD\\3. Desenvolvimento\\6. Automações Python\\Projeto SEARE\\workspace-projeto-seare\\Main\\Dados\\Historico Varredura SEI.xlsx'
